/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aerg.app.vistas;

import com.aerg.app.utilidades.InternalFrame;
import com.aerg.app.utilidades.Mensajes;

/**
 *
 * @author JULIOCESARMARTINEZ
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDPFormPadre = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIConsultarAsistencias = new javax.swing.JMenuItem();
        jMIRegistrarAsistencias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIConsultarCalificaciones = new javax.swing.JMenuItem();
        jMIRegistrarCalificaciones = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIRegistrarAlumno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión Parqueadero");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jDPFormPadre.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDPFormPadreLayout = new javax.swing.GroupLayout(jDPFormPadre);
        jDPFormPadre.setLayout(jDPFormPadreLayout);
        jDPFormPadreLayout.setHorizontalGroup(
            jDPFormPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jDPFormPadreLayout.setVerticalGroup(
            jDPFormPadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDPFormPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDPFormPadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMISalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMISalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registros");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMIConsultarAsistencias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIConsultarAsistencias.setText("Consultar");
        jMIConsultarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultarAsistenciasActionPerformed(evt);
            }
        });
        jMenu2.add(jMIConsultarAsistencias);

        jMIRegistrarAsistencias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIRegistrarAsistencias.setText("Registrar");
        jMIRegistrarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarAsistenciasActionPerformed(evt);
            }
        });
        jMenu2.add(jMIRegistrarAsistencias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vehículos");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMIConsultarCalificaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIConsultarCalificaciones.setText("Consultar");
        jMIConsultarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultarCalificacionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIConsultarCalificaciones);

        jMIRegistrarCalificaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIRegistrarCalificaciones.setText("Registrar");
        jMIRegistrarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarCalificacionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIRegistrarCalificaciones);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuarios");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMIRegistrarAlumno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIRegistrarAlumno.setText("Gestionar");
        jMIRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistrarAlumnoActionPerformed(evt);
            }
        });
        jMenu4.add(jMIRegistrarAlumno);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIConsultarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultarAsistenciasActionPerformed
        // TODO add your handling code here:
        this.abrirFormConsultarAsistencias();
    }//GEN-LAST:event_jMIConsultarAsistenciasActionPerformed

    private void jMIRegistrarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarAsistenciasActionPerformed
        // TODO add your handling code here:
        this.abrirFormRegistrarAsistencias();
    }//GEN-LAST:event_jMIRegistrarAsistenciasActionPerformed

    private void jMIConsultarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultarCalificacionesActionPerformed
        // TODO add your handling code here:
        this.abrirFormConsultarCalificaciones();
    }//GEN-LAST:event_jMIConsultarCalificacionesActionPerformed

    private void jMIRegistrarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarCalificacionesActionPerformed
        // TODO add your handling code here:
        this.abrirFormRegistrarCalificaciones();
    }//GEN-LAST:event_jMIRegistrarCalificacionesActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        // TODO add your handling code here:
        boolean confirma = Mensajes.mensajeConf("Salir del Sistema", "¿Seguro desea salir?");
        if(confirma){
            this.salir();
        }
        return;
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        this.abrirFormRegistarAlumnos();
    }//GEN-LAST:event_jMIRegistrarAlumnoActionPerformed

    private void salir(){
        dispose();
        System.exit(0);
    }
    
    private void abrirFormConsultarAsistencias(){
        new InternalFrame().llamarFormConsultaAsistencia();
    }
    
    private void abrirFormRegistrarAsistencias(){
        new InternalFrame().llamarFormRegistraAsistencia();
    }
    
    private void abrirFormConsultarCalificaciones(){
        new InternalFrame().llamarFormConsultaCalificacion();
    }
        
    private void abrirFormRegistrarCalificaciones(){
        new InternalFrame().llamarFormRegistraCalificacion();
    }
    
    private void abrirFormRegistarAlumnos(){
        new InternalFrame().llamarFormRegistraAlumno();
    }
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
         Set the Nimbus look and feel 

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDPFormPadre;
    private javax.swing.JMenuItem jMIConsultarAsistencias;
    private javax.swing.JMenuItem jMIConsultarCalificaciones;
    private javax.swing.JMenuItem jMIRegistrarAlumno;
    private javax.swing.JMenuItem jMIRegistrarAsistencias;
    private javax.swing.JMenuItem jMIRegistrarCalificaciones;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
